FROM debian:11
# Sicher Stellen das alle abhängigkeiten da sind
RUN apt update -y && apt upgrade -y \
    && apt-get install git python-dev curl systemctl -y 

RUN curl -fsSL https://ollama.com/install.sh | sh 

RUN systemctl start ollama.service && ollama pull deepseek-r1:7b

CMD systemctl start ollama.service && ollama run deepseek-r1:7b
